"""Experimental Finnish pedagogical core for Cognate Bridge.

Finnish is studied as the bridge language; Estonian cognates are the only target.
Entries are hand-curated for an experimental creator testbed (not a full dictionary).
"""

from __future__ import annotations

# (headword, pos, gloss_en, et_cognate | None)
# POS: n, v, adj, adv, pron, prep, conj, interj, num, particle
LEMMA_ROWS: list[tuple[str, str, str, str | None]] = [
    # Closed / high-frequency function words
    ("olla", "v", "to be", "olema"),
    ("ei", "v", "not (negation verb)", "ei"),
    ("ja", "conj", "and", "ja"),
    ("se", "pron", "it / that", "see"),
    ("hän", "pron", "he / she", "tema"),
    ("että", "conj", "that (complementizer)", "et"),
    ("oli", "v", "was (olla past)", None),
    ("mutta", "conj", "but", "aga"),
    ("minä", "pron", "I", "mina"),
    ("sinä", "pron", "you (sg)", "sina"),
    ("kun", "conj", "when / as", "kui"),
    ("niin", "adv", "so / thus", "nii"),
    ("jos", "conj", "if", "kui"),
    ("nyt", "adv", "now", "nüüd"),
    ("tämä", "pron", "this", "see"),
    ("voi", "v", "can / may (voida)", "võib"),
    ("he", "pron", "they", "nad"),
    ("kaikki", "pron", "all / everything", "kõik"),
    ("hyvä", "adj", "good", "hea"),
    ("sitten", "adv", "then", "siis"),
    ("miksi", "adv", "why", "miks"),
    ("miten", "adv", "how", "kuidas"),
    ("kyllä", "adv", "yes / indeed", "küll"),
    ("kiitos", "n", "thank you / thanks", "aitäh"),
    ("kanssa", "prep", "with", "koos"),
    ("tai", "conj", "or", "või"),
    ("me", "pron", "we", "meie"),
    ("ehkä", "adv", "maybe", "ehk"),
    ("hyvin", "adv", "well", "hästi"),
    ("vielä", "adv", "still / yet", "veel"),
    ("kuka", "pron", "who", "kes"),
    ("mikä", "pron", "what / which", "mis"),
    ("koska", "conj", "because", "sest"),
    ("tehdä", "v", "to do / make", "tegema"),
    ("paljon", "adv", "much / a lot", "palju"),
    ("ennen", "prep", "before", "enne"),
    ("aina", "adv", "always", "alati"),
    ("mies", "n", "man", "mees"),
    ("tietää", "v", "to know", "teadma"),
    ("isä", "n", "father", "isa"),
    ("äiti", "n", "mother", "ema"),
    ("aika", "n", "time", "aeg"),
    ("itse", "pron", "self", "ise"),
    ("myös", "adv", "also", "ka"),
    ("nainen", "n", "woman", "naine"),
    ("lapsi", "n", "child", "laps"),
    ("talo", "n", "house", "maja"),
    ("koti", "n", "home", "kodu"),
    ("vesi", "n", "water", "vesi"),
    ("maa", "n", "land / country / earth", "maa"),
    ("käsi", "n", "hand", "käsi"),
    ("pää", "n", "head", "pea"),
    ("silmä", "n", "eye", "silm"),
    ("suu", "n", "mouth", "suu"),
    ("jalka", "n", "foot / leg", "jalg"),
    ("sydän", "n", "heart", "süda"),
    ("veri", "n", "blood", "veri"),
    ("nimi", "n", "name", "nimi"),
    ("päivä", "n", "day", "päev"),
    ("yö", "n", "night", "öö"),
    ("vuosi", "n", "year", "aasta"),
    ("kuukausi", "n", "month", "kuu"),
    ("viikko", "n", "week", "nädal"),
    ("tunti", "n", "hour", "tund"),
    ("minuutti", "n", "minute", "minut"),
    ("aamu", "n", "morning", "hommik"),
    ("ilta", "n", "evening", "õhtu"),
    ("ruoka", "n", "food", "toit"),
    ("leipä", "n", "bread", "leib"),
    ("maito", "n", "milk", "piim"),
    ("kala", "n", "fish", "kala"),
    ("liha", "n", "meat", "liha"),
    ("omena", "n", "apple", "õun"),
    ("kahvi", "n", "coffee", "kohv"),
    ("tee", "n", "tea", "tee"),
    ("olut", "n", "beer", "õlu"),
    ("viini", "n", "wine", "vein"),
    ("kirja", "n", "book", "raamat"),
    ("sana", "n", "word", "sõna"),
    ("kieli", "n", "language / tongue", "keel"),
    ("koulu", "n", "school", "kool"),
    ("opettaja", "n", "teacher", "õpetaja"),
    ("opiskelija", "n", "student", "õpilane"),
    ("työ", "n", "work", "töö"),
    ("raha", "n", "money", "raha"),
    ("kaupunki", "n", "city", "linn"),
    ("kylä", "n", "village", "küla"),
    ("tie", "n", "road", "tee"),
    ("auto", "n", "car", "auto"),
    ("juna", "n", "train", "rong"),
    ("laiva", "n", "ship", "laev"),
    ("lentokone", "n", "airplane", "lennuk"),
    ("ovi", "n", "door", "uks"),
    ("ikkuna", "n", "window", "aken"),
    ("pöytä", "n", "table", "laud"),
    ("tuoli", "n", "chair", "tool"),
    ("sänky", "n", "bed", "voodi"),
    ("valo", "n", "light", "valgus"),
    ("tuli", "n", "fire", "tuli"),
    ("aurinko", "n", "sun", "päike"),
    ("kuu", "n", "moon", "kuu"),
    ("tähti", "n", "star", "täht"),
    ("sade", "n", "rain", "vihm"),
    ("lumi", "n", "snow", "lumi"),
    ("tuuli", "n", "wind", "tuul"),
    ("meri", "n", "sea", "meri"),
    ("järvi", "n", "lake", "järv"),
    ("joki", "n", "river", "jõgi"),
    ("metsä", "n", "forest", "mets"),
    ("puu", "n", "tree / wood", "puu"),
    ("kukka", "n", "flower", "lill"),
    ("koira", "n", "dog", "koer"),
    ("kissa", "n", "cat", "kass"),
    ("hevonen", "n", "horse", "hobune"),
    ("lintu", "n", "bird", "lind"),
    ("ystävä", "n", "friend", "sõber"),
    ("perhe", "n", "family", "pere"),
    ("veli", "n", "brother", "vend"),
    ("sisar", "n", "sister", "õde"),
    ("poika", "n", "boy / son", "poiss"),
    ("tyttö", "n", "girl", "tüdruk"),
    ("aviomies", "n", "husband", "abikaasa"),
    ("vaimo", "n", "wife", "naine"),
    ("rakas", "adj", "dear / beloved", "kallis"),
    ("iso", "adj", "big", "suur"),
    ("pieni", "adj", "small", "väike"),
    ("uusi", "adj", "new", "uus"),
    ("vanha", "adj", "old", "vana"),
    ("nuori", "adj", "young", "noor"),
    ("pitkä", "adj", "long / tall", "pikk"),
    ("lyhyt", "adj", "short", "lühike"),
    ("kaunis", "adj", "beautiful", "ilus"),
    ("ruma", "adj", "ugly", "kole"),
    ("kuuma", "adj", "hot", "kuum"),
    ("kylmä", "adj", "cold", "külm"),
    ("lämmin", "adj", "warm", "soe"),
    ("helppo", "adj", "easy", "kerge"),
    ("vaikea", "adj", "difficult", "raske"),
    ("nopea", "adj", "fast", "kiire"),
    ("hidas", "adj", "slow", "aeglane"),
    ("vahva", "adj", "strong", "tugev"),
    ("heikko", "adj", "weak", "nõrk"),
    ("täysi", "adj", "full", "täis"),
    ("tyhjä", "adj", "empty", "tühi"),
    ("oikea", "adj", "right / correct", "õige"),
    ("vasen", "adj", "left", "vasak"),
    ("ensimmäinen", "adj", "first", "esimene"),
    ("viimeinen", "adj", "last", "viimane"),
    ("toinen", "adj", "second / other", "teine"),
    ("sama", "adj", "same", "sama"),
    ("eri", "adj", "different", "eri"),
    ("valmis", "adj", "ready", "valmis"),
    ("vapaa", "adj", "free", "vaba"),
    ("tärkeä", "adj", "important", "tähtis"),
    ("mahdollinen", "adj", "possible", "võimalik"),
    ("tarpeellinen", "adj", "necessary", "vajalik"),
    ("mennä", "v", "to go", "minema"),
    ("tulla", "v", "to come", "tulema"),
    ("antaa", "v", "to give", "andma"),
    ("ottaa", "v", "to take", "võtma"),
    ("nähdä", "v", "to see", "nägema"),
    ("kuulla", "v", "to hear", "kuulma"),
    ("sanoa", "v", "to say", "ütlema"),
    ("puhua", "v", "to speak", "rääkima"),
    ("lukea", "v", "to read", "lugema"),
    ("kirjoittaa", "v", "to write", "kirjutama"),
    ("syödä", "v", "to eat", "sööma"),
    ("juoda", "v", "to drink", "jooma"),
    ("nukkua", "v", "to sleep", "magama"),
    ("herätä", "v", "to wake up", "ärkama"),
    ("asua", "v", "to live (reside)", "elama"),
    ("elää", "v", "to live (be alive)", "elama"),
    ("kuolla", "v", "to die", "surema"),
    ("ostaa", "v", "to buy", "ostma"),
    ("myydä", "v", "to sell", "müüma"),
    ("maksaa", "v", "to pay / cost", "maksma"),
    ("haluta", "v", "to want", "tahtma"),
    ("tarvita", "v", "to need", "vajama"),
    ("pitää", "v", "to like / hold / must", "pidama"),
    ("voida", "v", "to be able", "võima"),
    ("täytyä", "v", "must / have to", "pidama"),
    ("alkaa", "v", "to begin", "algama"),
    ("lopettaa", "v", "to finish / stop", "lõpetama"),
    ("odottaa", "v", "to wait", "ootama"),
    ("auttaa", "v", "to help", "aitama"),
    ("kysyä", "v", "to ask", "küsima"),
    ("vastata", "v", "to answer", "vastama"),
    ("ymmärtää", "v", "to understand", "mõistma"),
    ("ajatella", "v", "to think", "mõtlema"),
    ("tuntea", "v", "to feel / know (a person)", "tundma"),
    ("rakastaa", "v", "to love", "armastama"),
    ("vihata", "v", "to hate", "vihkama"),
    ("pelätä", "v", "to fear", "kartma"),
    ("nauraa", "v", "to laugh", "naerma"),
    ("itkeä", "v", "to cry", "nutma"),
    ("juosta", "v", "to run", "jooksma"),
    ("kävellä", "v", "to walk", "kõndima"),
    ("istua", "v", "to sit", "istuma"),
    ("seistä", "v", "to stand", "seisma"),
    ("maata", "v", "to lie (down)", "lamama"),
    ("nousta", "v", "to rise / get up", "tõusma"),
    ("laskea", "v", "to lower / count", "langema"),
    ("avata", "v", "to open", "avama"),
    ("sulkea", "v", "to close", "sulgema"),
    ("etsiä", "v", "to seek", "otsima"),
    ("löytää", "v", "to find", "leidma"),
    ("unohtaa", "v", "to forget", "unustama"),
    ("muistaa", "v", "to remember", "mäletama"),
    ("oppia", "v", "to learn", "õppima"),
    ("opettaa", "v", "to teach", "õpetama"),
    ("pelata", "v", "to play (a game)", "mängima"),
    ("laulaa", "v", "to sing", "laulma"),
    ("tanssia", "v", "to dance", "tantsima"),
    ("katsoa", "v", "to look / watch", "vaatama"),
    ("näyttää", "v", "to show", "näitama"),
    ("tuoda", "v", "to bring", "tooma"),
    ("viedä", "v", "to take (somewhere)", "viima"),
    ("jättää", "v", "to leave (behind)", "jätma"),
    ("jäädä", "v", "to stay / remain", "jääma"),
    ("vaihtaa", "v", "to change / exchange", "vahetama"),
    ("käyttää", "v", "to use", "kasutama"),
    ("tarjota", "v", "to offer", "pakkuma"),
    ("saada", "v", "to get / receive", "saama"),
    ("tulla", "v", "to come", "tulema"),
    ("tutustua", "v", "to get acquainted", "tutvuma"),
    ("kuulua", "v", "to belong / be heard", "kuuluma"),
    ("näkyä", "v", "to be visible", "näima"),
    ("tapahtua", "v", "to happen", "juhtuma"),
    ("onni", "n", "luck / happiness", "õnn"),
    ("suru", "n", "sorrow", "kurbus"),
    ("ilo", "n", "joy", "rõõm"),
    ("viha", "n", "anger / hate", "viha"),
    ("pelko", "n", "fear", "hirm"),
    ("toivo", "n", "hope", "lootus"),
    ("unelma", "n", "dream (aspiration)", "unistus"),
    ("uni", "n", "dream / sleep", "uni"),
    ("ongelma", "n", "problem", "probleem"),
    ("kysymys", "n", "question", "küsimus"),
    ("vastaus", "n", "answer", "vastus"),
    ("idea", "n", "idea", "idee"),
    ("tarina", "n", "story", "lugu"),
    ("uutinen", "n", "news (item)", "uudis"),
    ("kirje", "n", "letter", "kiri"),
    ("numero", "n", "number", "number"),
    ("väri", "n", "colour", "värv"),
    ("musta", "adj", "black", "must"),
    ("valkoinen", "adj", "white", "valge"),
    ("punainen", "adj", "red", "punane"),
    ("sininen", "adj", "blue", "sinine"),
    ("vihreä", "adj", "green", "roheline"),
    ("keltainen", "adj", "yellow", "kollane"),
    ("harmaa", "adj", "grey", "hall"),
    ("ruskea", "adj", "brown", "pruun"),
    ("yksi", "num", "one", "üks"),
    ("kaksi", "num", "two", "kaks"),
    ("kolme", "num", "three", "kolm"),
    ("neljä", "num", "four", "neli"),
    ("viisi", "num", "five", "viis"),
    ("kuusi", "num", "six", "kuus"),
    ("seitsemän", "num", "seven", "seitse"),
    ("kahdeksan", "num", "eight", "kaheksa"),
    ("yhdeksän", "num", "nine", "üheksa"),
    ("kymmenen", "num", "ten", "kümme"),
    ("sata", "num", "hundred", "sada"),
    ("tuhat", "num", "thousand", "tuhat"),
    ("täällä", "adv", "here", "siin"),
    ("siellä", "adv", "there", "seal"),
    ("missä", "adv", "where (at)", "kus"),
    ("minne", "adv", "where (to)", "kuhu"),
    ("mistä", "adv", "where (from)", "kust"),
    ("tänne", "adv", "to here", "siia"),
    ("sinne", "adv", "to there", "sinna"),
    ("pois", "adv", "away", "ära"),
    ("ulos", "adv", "out", "välja"),
    ("sisään", "adv", "in(to)", "sisse"),
    ("ylös", "adv", "up", "üles"),
    ("alas", "adv", "down", "alla"),
    ("edessä", "adv", "in front", "ees"),
    ("takana", "adv", "behind", "taga"),
    ("vieressä", "adv", "beside", "kõrval"),
    ("välillä", "adv", "between / sometimes", "vahel"),
    ("yhdessä", "adv", "together", "koos"),
    ("yksin", "adv", "alone", "üksi"),
    ("nopeasti", "adv", "quickly", "kiiresti"),
    ("hitaasti", "adv", "slowly", "aeglaselt"),
    ("hyvin", "adv", "well", "hästi"),
    ("huonosti", "adv", "badly", "halvasti"),
    ("todella", "adv", "really", "tõesti"),
    ("juuri", "adv", "just / exactly", "just"),
    ("vain", "adv", "only", "ainult"),
    ("jo", "adv", "already", "juba"),
    ("vielä", "adv", "still", "veel"),
    ("taas", "adv", "again", "jälle"),
    ("usein", "adv", "often", "tihti"),
    ("harvoin", "adv", "rarely", "harva"),
    ("koskaan", "adv", "ever / never (with ei)", "kunagi"),
    ("aina", "adv", "always", "alati"),
    ("joskus", "adv", "sometimes", "mõnikord"),
    ("heti", "adv", "immediately", "kohe"),
    ("pian", "adv", "soon", "varsti"),
    ("myöhään", "adv", "late", "hilja"),
    ("aikaisin", "adv", "early", "vara"),
    ("tänään", "adv", "today", "täna"),
    ("eilen", "adv", "yesterday", "eile"),
    ("huomenna", "adv", "tomorrow", "homme"),
    ("maanantai", "n", "Monday", "esmaspäev"),
    ("tiistai", "n", "Tuesday", "teisipäev"),
    ("keskiviikko", "n", "Wednesday", "kolmapäev"),
    ("torstai", "n", "Thursday", "neljapäev"),
    ("perjantai", "n", "Friday", "reede"),
    ("lauantai", "n", "Saturday", "laupäev"),
    ("sunnuntai", "n", "Sunday", "pühapäev"),
    ("kevät", "n", "spring", "kevad"),
    ("kesä", "n", "summer", "suvi"),
    ("syksy", "n", "autumn", "sügis"),
    ("talvi", "n", "winter", "talv"),
    ("sää", "n", "weather", "ilm"),
    ("lääkäri", "n", "doctor", "arst"),
    ("sairaala", "n", "hospital", "haigla"),
    ("apteekki", "n", "pharmacy", "apteek"),
    ("kauppa", "n", "shop", "pood"),
    ("markkinat", "n", "market", "turg"),
    ("pankki", "n", "bank", "pank"),
    ("posti", "n", "post / mail", "post"),
    ("poliisi", "n", "police", "politsei"),
    ("kirkko", "n", "church", "kirik"),
    ("kirjasto", "n", "library", "raamatukogu"),
    ("museo", "n", "museum", "muuseum"),
    ("teatteri", "n", "theatre", "teater"),
    ("elokuva", "n", "film", "film"),
    ("musiikki", "n", "music", "muusika"),
    ("laulu", "n", "song", "laul"),
    ("peli", "n", "game", "mäng"),
    ("urheilu", "n", "sport", "sport"),
    ("puhelin", "n", "telephone", "telefon"),
    ("tietokone", "n", "computer", "arvuti"),
    ("internet", "n", "internet", "internet"),
    ("sähköposti", "n", "email", "e-kiri"),
    ("osoite", "n", "address", "aadress"),
    ("kartta", "n", "map", "kaart"),
    ("lippu", "n", "ticket / flag", "pilet"),
    ("hotelli", "n", "hotel", "hotell"),
    ("ravintola", "n", "restaurant", "restoran"),
    ("kahvila", "n", "café", "kohvik"),
    ("huone", "n", "room", "tuba"),
    ("keittiö", "n", "kitchen", "köök"),
    ("kylpyhuone", "n", "bathroom", "vannituba"),
    ("puutarha", "n", "garden", "aed"),
    ("piha", "n", "yard", "õu"),
    ("seinä", "n", "wall", "sein"),
    ("lattia", "n", "floor", "põrand"),
    ("katto", "n", "ceiling / roof", "lagi"),
    ("avain", "n", "key", "võti"),
    ("laukku", "n", "bag", "kott"),
    ("lompakko", "n", "wallet", "rahakott"),
    ("vaate", "n", "garment / clothes", "riie"),
    ("paita", "n", "shirt", "särk"),
    ("housut", "n", "trousers", "püksid"),
    ("kenkä", "n", "shoe", "king"),
    ("hattu", "n", "hat", "müts"),
    ("takki", "n", "coat", "mantel"),
    ("meikka", "n", "make-up", None),
    ("saippua", "n", "soap", "seep"),
    ("hammas", "n", "tooth", "hammas"),
    ("hius", "n", "hair (strand)", "juuksed"),
    ("parta", "n", "beard", "habe"),
    ("nahka", "n", "skin / leather", "nahk"),
    ("luu", "n", "bone", "luu"),
    ("lihas", "n", "muscle", "lihas"),
    ("sairaus", "n", "illness", "haigus"),
    ("kipu", "n", "pain", "valu"),
    ("lääke", "n", "medicine", "ravim"),
    ("terveys", "n", "health", "tervis"),
    ("voima", "n", "power / strength", "jõud"),
    ("energia", "n", "energy", "energia"),
    ("ilma", "n", "air / weather", "õhk"),
    ("kaasu", "n", "gas", "gaas"),
    ("öljy", "n", "oil", "õli"),
    ("metalli", "n", "metal", "metall"),
    ("kivi", "n", "stone", "kivi"),
    ("hiekka", "n", "sand", "liiv"),
    ("pöly", "n", "dust", "tolm"),
    ("lika", "n", "dirt", "mustus"),
    ("puhdas", "adj", "clean", "puhas"),
    ("likainen", "adj", "dirty", "must"),
    ("märkä", "adj", "wet", "märg"),
    ("kuiva", "adj", "dry", "kuiv"),
    ("pehmeä", "adj", "soft", "pehme"),
    ("kova", "adj", "hard", "kõva"),
    ("terävä", "adj", "sharp", "terav"),
    ("tylissä", "adj", "dull", None),
    ("kirkas", "adj", "bright / clear", "hele"),
    ("pimeä", "adj", "dark", "pime"),
    ("äänekäs", "adj", "loud", "valju"),
    ("hiljainen", "adj", "quiet", "vaikne"),
    ("makea", "adj", "sweet", "magus"),
    ("suolainen", "adj", "salty", "soolane"),
    ("hapan", "adj", "sour", "hapu"),
    ("karvas", "adj", "bitter", "mõru"),
    ("tuore", "adj", "fresh", "värske"),
    ("pilaantunut", "adj", "spoiled", "riknenud"),
    ("halpa", "adj", "cheap", "odav"),
    ("kallis", "adj", "expensive", "kallis"),
    ("rikas", "adj", "rich", "rikas"),
    ("köyhä", "adj", "poor", "vaene"),
    ("onnellinen", "adj", "happy", "õnnelik"),
    ("surullinen", "adj", "sad", "kurb"),
    ("vihainen", "adj", "angry", "vihane"),
    ("väsynyt", "adj", "tired", "väsinud"),
    ("nälkäinen", "adj", "hungry", "näljane"),
    ("janoinen", "adj", "thirsty", "janune"),
    ("sairas", "adj", "ill", "haige"),
    ("terve", "adj", "healthy", "terve"),
    ("kiireinen", "adj", "busy", "hõivatud"),
    ("vapaa", "adj", "free", "vaba"),
    ("turvallinen", "adj", "safe", "turvaline"),
    ("vaarallinen", "adj", "dangerous", "ohtlik"),
    ("kiinnostava", "adj", "interesting", "huvitav"),
    ("tylsä", "adj", "boring", "igav"),
    ("hauska", "adj", "fun / funny", "lõbus"),
    ("vakava", "adj", "serious", "tõsine"),
    ("ystävällinen", "adj", "friendly", "sõbralik"),
    ("kohtelias", "adj", "polite", "viisakas"),
    ("rehellinen", "adj", "honest", "aus"),
    ("ahkera", "adj", "diligent", "tubli"),
    ("laiska", "adj", "lazy", "laisk"),
    ("älykäs", "adj", "intelligent", "intelligentne"),
    ("tyhmä", "adj", "stupid", "loll"),
    ("luova", "adj", "creative", "loov"),
    ("käytännöllinen", "adj", "practical", "praktiline"),
    ("teoreettinen", "adj", "theoretical", "teoreetiline"),
    ("kansallinen", "adj", "national", "rahvuslik"),
    ("kansainvälinen", "adj", "international", "rahvusvaheline"),
    ("paikallinen", "adj", "local", "kohalik"),
    ("yleinen", "adj", "general / common", "üldine"),
    ("erityinen", "adj", "special", "eriline"),
    ("normaali", "adj", "normal", "normaalne"),
    ("outo", "adj", "strange", "veider"),
    ("tuttu", "adj", "familiar", "tuttav"),
    ("tuntematon", "adj", "unknown", "tundmatu"),
    ("julkinen", "adj", "public", "avalik"),
    ("yksityinen", "adj", "private", "era"),
    ("virallinen", "adj", "official", "ametlik"),
    ("epävirallinen", "adj", "unofficial", "mitteametlik"),
    # Gradation exemplars (pedagogical)
    ("matto", "n", "carpet / mat", "vaip"),
    ("mato", "n", "worm", "uss"),
    ("puku", "n", "suit / costume", "ülikond"),
    ("suku", "n", "family / kin", "suguvõsa"),
    ("laki", "n", "law", "seadus"),
    ("järki", "n", "reason / sense", "mõistus"),
    ("hinta", "n", "price", "hind"),
    ("ranta", "n", "shore / beach", "rand"),
    ("kerta", "n", "time (occasion)", "kord"),
    ("tahto", "n", "will", "tahe"),
    ("lehti", "n", "leaf / newspaper", "leht"),
    ("suksi", "n", "ski", "suusk"),
    ("tieto", "n", "knowledge / data", "teadmine"),
    ("sota", "n", "war", "sõda"),
    ("kota", "n", "hut", "koda"),
    ("pata", "n", "pot", "pada"),
    ("katu", "n", "street", "tänav"),
    ("satu", "n", "fairy tale", "muinasjutt"),
    ("luku", "n", "number / chapter", "peatükk"),
    ("reki", "n", "sledge", "regi"),
    ("mäki", "n", "hill", "mägi"),
    ("väki", "n", "people / folk", "rahvas"),
    ("häät", "n", "wedding", "pulm"),
    ("panna", "v", "to put", "panema"),
    ("purra", "v", "to bite", "hammustama"),
    ("surra", "v", "to mourn", "leinama"),
    ("piirtää", "v", "to draw", "joonistama"),
    ("kiertää", "v", "to circle / tour", "keerama"),
    ("saattaa", "v", "to escort / may", "saatma"),
    ("laittaa", "v", "to put / prepare", "panema"),
    ("ajaa", "v", "to drive", "sõitma"),
    ("luoda", "v", "to create", "looma"),
]


def unique_lemmas() -> list[dict]:
    """Dedupe by headword+pos, prefer rows that carry an Estonian cognate."""
    best: dict[tuple[str, str], dict] = {}
    for headword, pos, gloss, et in LEMMA_ROWS:
        key = (headword.lower(), pos)
        row = {
            "headword": headword,
            "part_of_speech": pos,
            "gloss_en": gloss,
            "glosses_en": [gloss],
            "et": et,
        }
        prior = best.get(key)
        if prior is None or (prior.get("et") is None and et):
            best[key] = row
    return sorted(best.values(), key=lambda r: (r["headword"].lower(), r["part_of_speech"]))
