import { BookOpen, CheckCircle2, CircleDashed } from 'lucide-react';
import { Link } from 'react-router-dom';
import type { Cognate, CorrespondenceRule } from '../services/api';
import './CorrespondencePanel.css';

/** Best-effort map from sound-law code prefixes to decoder rule-card slugs. */
const SOUND_LAW_RULE_SLUGS: { prefix: string; slug: string }[] = [];

function ruleCardSlugForCode(code: string | null | undefined): string | null {
  if (!code) return null;
  for (const entry of SOUND_LAW_RULE_SLUGS) {
    if (code === entry.prefix || code.startsWith(`${entry.prefix}.`) || code.startsWith(`${entry.prefix}_`)) {
      return entry.slug;
    }
  }
  return null;
}

/**
 * Shows a bridge word's cognates in each target language, with the rule that relates
 * them.
 *
 * This is the feature the schema was designed for, so the panel is deliberate about
 * showing *why* a form is here, not just that it is. A Germanic cognate is quoted from
 * the Wordbouk's etymological section and needs no justification beyond its source. A
 * Romance cognate was generated by applying a rule to the Interlingua prototype and then
 * checked against an open lexicon, so it carries both the rule and whether the check
 * passed. Presenting a prediction and an attestation as if they were the same claim would
 * be the easiest way to make this feature quietly dishonest.
 */

interface Props {
  cognates: Cognate[];
  /** Hides the heading when the panel is embedded in a card that already has one. */
  bare?: boolean;
  /** When set, render this copy instead of the empty-state paragraph. */
  emptyLabel?: string;
}

function confidenceLabel(cognate: Cognate): string {
  if (cognate.provenance === 'parsed') return 'Attested in the source dictionary';
  if (cognate.provenance === 'curated') return 'Etymological cognate link';
  if (cognate.provenance === 'similarity') {
    return 'Surface-transparent match on a translation pair';
  }
  if (cognate.validated_against) {
    return `Predicted by rule, confirmed in ${cognate.validated_against}`;
  }
  return 'Predicted by rule, not confirmed against a lexicon';
}

function rulesFor(cognate: Cognate): CorrespondenceRule[] {
  if (cognate.rules && cognate.rules.length > 0) return cognate.rules;
  return cognate.rule ? [cognate.rule] : [];
}

function uniqueRules(cognates: Cognate[]): CorrespondenceRule[] {
  const seen = new Set<number>();
  const rules: CorrespondenceRule[] = [];
  for (const cognate of cognates) {
    for (const rule of rulesFor(cognate)) {
      if (seen.has(rule.id)) continue;
      seen.add(rule.id);
      rules.push(rule);
    }
  }
  return rules;
}

export function SoundLawStack({ rules }: { rules: CorrespondenceRule[] }) {
  if (rules.length === 0) return null;
  return (
    <div className="sound-laws">
      {rules.map((rule) => (
        <SoundLawBlock key={rule.id} rule={rule} />
      ))}
    </div>
  );
}

function SoundLawBlock({ rule }: { rule: CorrespondenceRule }) {
  const practiceSlug = ruleCardSlugForCode(rule.code);

  return (
    <div className="correspondence__rule">
      {rule.name && <p className="correspondence__rule-name">{rule.name}</p>}
      {rule.notation && <p className="correspondence__rule-notation">{rule.notation}</p>}
      {!rule.name && <p className="correspondence__rule-text">{rule.description}</p>}
      {rule.example_bridge && rule.example_target && (
        <p className="correspondence__rule-example">
          <code>{rule.example_bridge}</code>
          <span aria-hidden="true"> &rarr; </span>
          <code>{rule.example_target}</code>
        </p>
      )}
      {rule.name && rule.description && (
        <p className="correspondence__rule-text">{rule.description}</p>
      )}
      <p className="correspondence__rule-source">
        <BookOpen size={12} aria-hidden="true" /> {rule.source_note}
      </p>
      {practiceSlug && (
        <p className="correspondence__practice">
          <Link to={`/rules/${practiceSlug}`}>Practice this rule</Link>
        </p>
      )}
    </div>
  );
}

export default function CorrespondencePanel({ cognates, bare = false, emptyLabel }: Props) {
  if (cognates.length === 0) {
    if (bare && !emptyLabel) return null;
    return (
      <div className="correspondence">
        {!bare && <h3 className="section-heading">Correspondences</h3>}
        <p className="correspondence__empty">
          {emptyLabel ??
            'No cognate is recorded for this word. For a bridge language that usually means the form is native to it rather than shared across the family.'}
        </p>
      </div>
    );
  }

  // Grouped by language rather than listed flat: a word can have several attested forms
  // in one language (English `abundance` and `abundancy`), and the question a learner is
  // asking is "what is this in German", not "what are all the forms".
  const byLanguage = new Map<string, Cognate[]>();
  for (const cognate of cognates) {
    const key = cognate.target_language.code;
    byLanguage.set(key, [...(byLanguage.get(key) ?? []), cognate]);
  }

  return (
    <div className="correspondence">
      {!bare && <h3 className="section-heading">Correspondences</h3>}
      <ul className="correspondence__list">
        {[...byLanguage.entries()].map(([code, group]) => {
          const language = group[0]!.target_language;
          const rules = uniqueRules(group);

          return (
            <li key={code} className="correspondence__row">
              <div className="correspondence__lang">
                <span className="correspondence__code">{code}</span>
                <span className="correspondence__name">{language.name}</span>
              </div>

              <div className="correspondence__forms">
                {group.map((cognate) => (
                  <span
                    key={cognate.id}
                    className="correspondence__form"
                    title={confidenceLabel(cognate)}
                  >
                    {cognate.target_word}
                    {cognate.provenance === 'parsed' ? (
                      <CheckCircle2 size={13} className="correspondence__icon is-attested" />
                    ) : cognate.validated_against ? (
                      <CheckCircle2 size={13} className="correspondence__icon is-confirmed" />
                    ) : (
                      <CircleDashed size={13} className="correspondence__icon is-predicted" />
                    )}
                  </span>
                ))}
              </div>

              {rules.length > 0 && (
                <div className="correspondence__rules">
                  {rules.map((rule) => (
                    <SoundLawBlock key={rule.id} rule={rule} />
                  ))}
                </div>
              )}
            </li>
          );
        })}
      </ul>

      <p className="correspondence__legend">
        <CheckCircle2 size={12} className="correspondence__icon is-attested" /> attested or
        lexicon-confirmed
        <span className="correspondence__legend-gap" />
        <CircleDashed size={12} className="correspondence__icon is-predicted" /> predicted, not
        confirmed
      </p>
    </div>
  );
}
